# Generated by Django 4.2.11 on 2026-05-23 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_add_brand_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blast", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MondlyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mondly_user_id", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(default="English", max_length=100)),
                ("level", models.PositiveSmallIntegerField(default=1)),
                ("points", models.PositiveIntegerField(default=0)),
                ("best_streak", models.PositiveIntegerField(default=0)),
                ("learning_minutes", models.PositiveIntegerField(default=0)),
                ("lessons_completed", models.PositiveIntegerField(default=0)),
                ("words_learned", models.PositiveIntegerField(default=0)),
                ("phrases_learned", models.PositiveIntegerField(default=0)),
                ("last_active_on", models.DateTimeField(blank=True, null=True)),
                ("mondly_team", models.CharField(blank=True, max_length=255)),
                ("imported_at", models.DateTimeField(auto_now=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mondly_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_objects",
                        to="organizations.organization",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mondly_records",
                        to="blast.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-imported_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "email"],
                        name="blast_mondl_organiz_c7edc5_idx",
                    )
                ],
                "unique_together": {("organization", "email", "language")},
            },
        ),
    ]
