# Generated by Django 4.2.11 on 2026-05-29 15:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_empty_class_rate'),
        ('blast', '0002_mondly_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmptyClassSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empty_sessions', to='blast.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='organizations.organization')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('organization', 'group', 'date')},
            },
        ),
    ]
