# Generated by Django 4.2.11 on 2026-06-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blast', '0003_emptyclasssession'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateclient',
            name='send_monthly_report',
            field=models.BooleanField(default=False),
        ),
    ]
