# Generated by Django 4.2.11 on 2026-07-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blast', '0005_add_report_type_to_corporate_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateclient',
            name='report_type',
            field=models.CharField(choices=[('ytd', 'Year to Date'), ('monthly', 'Mensual'), ('q1', 'Q1 (Ene–Mar)'), ('q2', 'Q2 (Abr–Jun)'), ('q3', 'Q3 (Jul–Sep)'), ('q4', 'Q4 (Oct–Dic)')], default='ytd', max_length=10),
        ),
    ]
