# Generated by Django 4.2.11 on 2026-05-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("corporate_client", "Corporate Client"),
                    ("student", "Student"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
