# Generated by Django 4.2.11 on 2026-05-22 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blast", "0001_initial"),
        ("accounts", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="corporate_client",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_accounts",
                to="blast.corporateclient",
            ),
        ),
    ]
