# Generated by Django 4.2.11 on 2026-06-08 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_empty_class_rate'),
        ('accounts', '0003_link_corporate_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='requested_organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='organizations.organization'),
        ),
    ]
