# Generated by Django 4.2.11 on 2026-05-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
