# Generated by Django 4.2.11 on 2026-05-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_add_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='empty_class_rate',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
        ),
    ]
